-- 코드를 입력하세요
-- 상품코드 별 매출액(판매가 PRICE * 판매량 SALES_AMOUNT) 합계
-- 매출액 기준 내림차순(DESC) 상품 코드 기준 (ASC)
SELECT PR.PRODUCT_CODE, PR.PRICE * SUM(SALES_AMOUNT) AS SALES
FROM PRODUCT AS PR
JOIN OFFLINE_SALE AS OS
ON PR.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY PR.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC