-- 코드를 입력하세요
-- 2022년 10월 5일에 등록된
SELECT BOARD_ID, WRITER_ID, TITLE, PRICE,
    CASE
        WHEN UGB.STATUS = "DONE" 
        THEN '거래완료'
        WHEN UGB.STATUS = "SALE"
        THEN '판매중'
        WHEN UGB.STATUS = "RESERVED"
        THEN '예약중'
        END AS STATUS
FROM USED_GOODS_BOARD AS UGB
WHERE CREATED_DATE = '2022-10-05'
ORDER BY BOARD_ID DESC